### ISSUE TITLE
 Checklist for Private Alpha 2.0

### ISSUE THREAD

**Issue by real2two** [smpfree/core#2]
[player] means themselves without needing @p/s.

- [x] `/gamemode` <mode> [player]
    - [x] All Modes
       - [x] `adventure`
       - [x] `creative`
       - [x] `spectator`
       - [x] `survival`
    - [x] Entities
        Not going to make: `@a`
        Not going to make: `@p/s` 
        Not going to make: `@r`
        - [x] `[player]`
- [x] `/gamerule` <rule> [value]
    - [x] `announceAdvancements`
    - [x] `commandBlockOutput`
    - [x] `disableElytraMovementCheck`
    - [x] `doDaylightCycle`
    - [x] `doEntityDrops`
    - [x] `doFireTick`
    - [x] `doLimitedCrafting`
    - [x] `doMobLoot`
    - [x] `doMobSpawning`
    - [x] `doTileDrops`
    - [x] `doWeatherCycle`
    - [x] `keepInventory`
    - [x]  `logAdminCommands`
    - [x] `maxCommandChainLength`
    - [x] `maxEntityCramming`
    - [x] `mobGriefing`
    - [x] `naturalRegeneration`
    - [x] `randomTickSpeed`
    - [x] `reducedDebugInfo`
    - [x] `sendCommandFeedback`
    - [x] `showDeathMessages`
    - [x] `spawnRadius`
    - [x] `spectatorsGenerateChunks`
- [x] `/clear` [player]
    Not going to make: `@a`
    Not going to make: `@p/s`
    Not going to make: `@r`
    - [x] `[player]`
- [x] `/defaultgamemode` <mode>
    - [x] `adventure`
    - [x] `creative`
    - [x] `spectator`
    - [x] `survival`
- [x] `/difficulty` [mode]
    - [x] `peaceful`
    - [x] `easy`
    - [x] `normal`
    - [x] `hard`
- [x] `/effect` <give/clear> <entity> [effect]
    - [x] `give`
        - [x] Entities
            - [x] Player
            Not going to make: `@a`
            Not going to make: `@p/s`
            Not going to make: `@r`
            Not going to make: `@e`
        - [x] Effects
            - [x] `speed (1)`
            - [x] `slowness (2)`
            - [x] `haste (3)`
            - [x] `mining_fatigue (4)`
            - [x] `strength (5)`
            - [x] `instant_health (6)`
            - [x] `instant_damage (7)`
            - [x] `jump_boost (8)`
            - [x] `nausea (9)`
            - [x] `regeneration (10)`
            - [x] `resistance (11)`
            - [x] `fire_resistance (12)`
            - [x] `water_breathing (13)`
            - [x] `invisibility (14)`
            - [x] `blindness (15)`
            - [x] `night_vision (16)`
            - [x] `hunger (17)`
            - [x] `weakness (18)`
            - [x] `poison (19)`
            - [x] `wither (20)`
            - [x] `health_boost (21)`
            - [x] `absorption (22)`
            - [x] `saturation (23)`
            - [x] `glowing (24)`
            - [x] `levitation (25)`
            - [x] `luck (26)`
            - [x] `unluck (27)`
            - [x] `slow_falling (28)`
            - [x] `conduit_power (29)`
            - [x] `dolphins_grace (30)`
            - [x] `bad_omen (31)`
            - [x] `hero_of_the_village (32)`
    - [x] `clear`
        - [x] Player
        Not going to make: `@a`
        Not going to make: `@p/s`
- [x] `/enchant` <player> <enchantment> <level>
    - [x] Entities
        - [x] Player
        Not going to make: `@p/s`
        Not going to make: `@a `
        Not going to make: `@r`
    - [x] Enchantments    
        - [x] `protection`
        - [x] `fire_protection`
        - [x] `feather_falling`
        - [x] `blast_protection`
        - [x] `projectile_protection`
        - [x] `respiration`
        - [x] `aqua_infinity`
        - [x] `thorns`
        - [x] `depth_strider`
        - [x] `frost_walker`
        - [x] `binding_curse`
        - [x] `sharpness`
        - [x] `smite`
        - [x] `bane_of_arthropods`
        - [x] `knockback`
        - [x] `first_aspect`
        - [x] `looting`
        - [x] `sweeping_edge`
        - [x] `efficiency`
        - [x] `silk_touch`
        - [x] `fortune`
        - [x] `luck_of_the_sea`
        - [x] `lure`
        - [x] `power`
        - [x] `punch`
        - [x] `flame`
        - [x] `infinity`
        - [x] `channeling`
        - [x] `riptide`
        - [x] `loyalty`
        - [x] `mending`
        - [x] `vanishing_curse`
        - [x] `unbreaking`
- [x] `/weather` <weather>
    - [x] `clear`
    - [x] `rain`
    - [x] `thunder`
- [x] `/xp` <type> <player> [amount] <points/levels>
    - [x] Types:
        - [x] `add`
            - [x] `points`
            - [x] `levels`
        - [x] `query`
            - [x] `points`
            - [x] `levels`
        - [x] `set`
            - [x] `points`
            - [x] `levels`
    - [x] Entities
        - [x] Player (add)
        - [x] Player (query)
        - [x] Player (set)
        Not going to make: `@p/s` (add)
        Not going to make: `@a` (add)
        Not going to make: `@r` (add)
        Not going to make: `@p/s` (query)
        Not going to make: `@a` (query)
        Not going to make: `@r` (query)
        Not going to make: `@p/s` (set)
        Not going to make: `@a` (set)
        Not going to make: `@r` (set)
- [x] `/time` <type> [query type] <type>
    Not going to make: `add` <time>
     Not going to make: `query` 
         Not going to make: `day`
         Not going to make: `daytime`
         Not going to make: `gametime`
    - [x] `set` (but "set" is not required)
        - [x] `day`
        - [x] `noon`
        - [x] `night`
        - [x] `midnight`
        Not going to make: `[time]`
- [x] `/summon` <entity> [x] [y] [z]
    Not going to make: Summon Coords (not a entity)
    - [x] `area_effect_cloud`
    - [x] `armor_stand`
    - [x] `arrow`
    - [] `bat`
    - [x] `blaze`
    - [x] `boat`
    - [x] `cave_spider`
    - [x] `chest_minecart`
    - [x] `chicken`
    - [x] `cod`
    - [x] `cow` (only one tested)
    - [x] `creeper`
    - [x] `dolphin`
    - [x] `donkey`
    - [x] `dragon_fireball`
    - [x] `drowned`
    - [x] `egg`
    - [x] `elder_guardian`
    - [x] `ender_crystal`
    - [x] `ender_dragon`
    - [x] `ender_pearl`
    - [x] `enderman`
    - [x] `endermite`
    - [x] `evoker`
    - [x] `evoker_fangs`
    - [x] `experience_bottle`
    - [x] `experience_orb`
    - [x] `falling_block`
    - [x] `fireball`
    - [x] `firework_rocket`
    - [x] `furnace_minecart`
    - [x] `ghast`
    - [x] `giant`
    - [x] `guardian`
    - [x] `hopper_minecraft`
    - [x] `horse`
    - [x] `husk`
    - [x] `illusioner`
    - [x] `iron_golem`
    - [x] `item`
    - [x] `item_frame`
    - [x] `leash_knot`
    - [x] `lightning_bolt`
    - [x] `llama`
    - [x] `llama_spit`
    - [x] `magma_cube`
    - [x] `minecart`
    - [x] `mooshroom`
    - [x] `mule`
    - [x] `ocelot`
    - [x] `painting`
    - [x] `parrot`
    - [x] `phantom`
    - [x] `pig`
    - [x] `polar_bear`
    - [x] `potion`
    - [x] `pufferfish`
    - [x] `rabbit`
    - [x] `salmon`
    - [x] `sheep`
    - [x] `shulker`
    - [x] `shulker_bullet`
    - [x] `sliverfish`
    - [x] `skeleton`
    - [x] `skeleton_horse`
    - [x] `slime`
    - [x] `small_fireball`
    - [x] `snow_golem`
    - [x] `snowball`
    - [x] `spawner_minecart`
    - [x] `spectral_arrow`
    - [x] `spider`
    - [x] `squid`
    - [x] `stray`
    - [x] `tnt`
    - [x] `tnt_minecart`
    - [x] `trident`
    - [x] `tropical_fish`
    - [x] `turtle`
    - [x] `vex`
    - [x] `villager`
    - [x] `vindicator`
    - [x] `witch`
    - [x] `wither`
    - [x] `wither_skeleton`
    - [x] `wither_skull`
    - [x] `wolf`
    - [x] `zombie`
    - [x] `zombie_horse`
    - [x] `zombie_pigman`
    - [x] `zombie_villager`
- [x] `/op` <player>
- [x] `/deop` <player>
- [x] `/tp` 
    - [x] Event Entity (this entity is teleported)
        - [x] Player
        Not going to make: `@p/s`
        Not going to make: `@a`
        Not going to make: `@r`
    - [x] Location Entity (this is the location)
        Not going to make: `@p/s`
        Not going to make: `@a`
        Not going to make: `@r`
        Not going to make: `@e`
        - [x] Player
        Not going to make: `[coords]`
